### ISSUE TITLE
"FAILED" Status: FAILED. Reason: Requires capabilities : [CAPABILITY_NAMED_IAM]

### ISSUE THREAD

**Issue by dazzlersa** [aws-samples/amazon-qldb-financialwallet-crud-aws-samples-v2#1]
Hoping for some help, I have followed the instructions to a T, and also tried 3 times after deleting the cloudstack.
But no matter what I try, I keep getting the same error:

`Looking for config file [samconfig.toml] :  Found
        Reading default arguments  :  Success

        Setting default arguments for 'sam deploy'
        =========================================
        Stack Name [financial-wallet]: 
        AWS Region [us-east-1]: 
        #Shows you resources changes to be deployed and require a 'Y' to initiate deploy
        Confirm changes before deploy [Y/n]: y
        #SAM needs permission to be able to create roles to connect to the resources in your template
        Allow SAM CLI IAM role creation [Y/n]: y
        #Preserves the state of previously provisioned resources when an operation fails
        Disable rollback [Y/n]: y
        createtablefunc may not have authorization defined, Is this okay? [y/N]: y
        indexfunc may not have authorization defined, Is this okay? [y/N]: y
        createaccountfunc may not have authorization defined, Is this okay? [y/N]: y
        checkfundsfunc may not have authorization defined, Is this okay? [y/N]: y
        addfundsfunc may not have authorization defined, Is this okay? [y/N]: y
        withdrawfundsfunc may not have authorization defined, Is this okay? [y/N]: y
        Save arguments to configuration file [Y/n]: y
        SAM configuration file [samconfig.toml]: 
        SAM configuration environment [default]: 

        Looking for resources needed for deployment:
         Managed S3 bucket: aws-sam-cli-managed-default-samclisourcebucket-1dcsy784si0cu
         A different default S3 bucket can be set in samconfig.toml

        Saved arguments to config file
        Running 'sam deploy' for future deployments will use the parameters saved above.
        The above parameters can be changed by modifying samconfig.toml
        Learn more about samconfig.toml syntax at 
        https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html

File with same data already exists at financial-wallet/7f39e5f60fc98f8a121c4058447f521e, skipping upload
File with same data already exists at financial-wallet/7f39e5f60fc98f8a121c4058447f521e, skipping upload
File with same data already exists at financial-wallet/7f39e5f60fc98f8a121c4058447f521e, skipping upload
File with same data already exists at financial-wallet/7f39e5f60fc98f8a121c4058447f521e, skipping upload
File with same data already exists at financial-wallet/7f39e5f60fc98f8a121c4058447f521e, skipping upload
File with same data already exists at financial-wallet/7f39e5f60fc98f8a121c4058447f521e, skipping upload

        Deploying with following values
        ===============================
        Stack name                   : financial-wallet
        Region                       : us-east-1
        Confirm changeset            : True
        Disable rollback             : True
        Deployment s3 bucket         : aws-sam-cli-managed-default-samclisourcebucket-1dcsy784si0cu
        Capabilities                 : ["CAPABILITY_IAM"]
        Parameter overrides          : {}
        Signing Profiles             : {}

Initiating deployment
=====================
File with same data already exists at financial-wallet/03928f93058217900495f328b62771c1.template, skipping upload

Waiting for changeset to be created..
Error: Failed to create changeset for the stack: financial-wallet, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Requires capabilities : [CAPABILITY_NAMED_IAM]`

Am I missing something silly?

**Comment by januraamazon** [comment]
Please edit the "samconfig.toml" and modify/add

capabilities = "CAPABILITY_NAMED_IAM"

Save the file
